### ISSUE TITLE
Getting MySql related error while installation

### ISSUE THREAD

**Issue by yognsk** [OfficeStack/OpenSkedge#105]
Hello,

I am getting an error upon installing software. Its cPanel server and want to add it on subdomain. 
Please check below error and have look on it.
# 

root@server [//home/snwn/shift.snwntechsolution.com]# php app/console doctrine:database:create
Could not create database for connection named `openskedge`
# SQLSTATE[HY000] [1045] Access denied for user 'YOUR_USER'@'localhost' (using password: YES)

root@server [//home/snwn/shift.snwntechsolution.com]# php app/console doctrine:schema:update --force
  [PDOException]
  SQLSTATE[HY000] [1045] Access denied for user 'YOUR_USER'@'localhost' (using password: YES)
# doctrine:schema:update [--complete] [--dump-sql] [--force] [--em[="..."]]

Thanks!

**Comment by CokkocZateki** [comment]
you need to edit parameters.yml with your details
