### ISSUE TITLE
Schedule Start/End hour

### ISSUE THREAD

**Issue by ghost** [OfficeStack/OpenSkedge#108]
The demo system can't create schedules with 24 hours. The most you can get is a 12 hour schedule from AM-PM.

**Comment by ghost** [comment]
If you have 3 shifts in a day. 24 hours / 3 = 8 hours. How do you schedule this if you can only create 12 hours in the settings.

**Comment by CokkocZateki** [comment]
this would work soo much better for me since our shifts differ from 8 hours to 10 hours or 12 hours

**Comment by maxfierke** [comment]
@Ldiocotlhe @CokkocZateki you can have the start time set to 12AM and the end time set to 12AM if you go to `/app/settings`. That will give you the full 24 hours.
