### ISSUE TITLE
The installation error in "php composer.phar install"

### ISSUE THREAD

**Issue by dolyv98** [OfficeStack/OpenSkedge#120]
Hello, I'm trying to install OpenSkedge and I got some error at this step.
![screenshot 170](https://user-images.githubusercontent.com/36594004/49341162-2b70f200-f67c-11e8-883e-7862ef069e89.png)
![screenshot 171](https://user-images.githubusercontent.com/36594004/49341164-2f9d0f80-f67c-11e8-83a6-30567c7258d0.png)
Does anyone know how to solve this problem? Thanks...

**Comment by maxfierke** [comment]
@dolyv98 you probably need to `sudo apt-get install php7.2-intl php7.2-dom`
