### ISSUE TITLE
[reported] shift trading (under "posted shifts") to work

### ISSUE THREAD

**Issue by maxfierke** [OfficeStack/OpenSkedge#73]
Received report that "Every attempt returns an error ("Shift could not be posted! Invalid data"

**Comment by Kazgratz** [comment]
Ran into the same issue.  Issue is in ShftController.php where it is not letting isValid pass due to status not being filled.

**Comment by maxfierke** [comment]
Actual fix is in 139d8bfbcf2aebb74cf02307ad66fe3f83cdc95c. Only took me two years to get around to :stuck_out_tongue:
