### ISSUE TITLE
Time clock not working

### ISSUE THREAD

**Issue by jalewellyn** [OfficeStack/OpenSkedge#77]
Hello,

When I attempt to clock-in I receive a blank white screen.The time on the time clock also appears to be wrong? How can I get the time clock working and set it to the correct time.

Thank you!

**Comment by auriculogenesis** [comment]
For those who have shared servers w/poor support, add <code>date_default_timezone_set('America/Los_Angeles');</code> (change it accordingly to your timezone) to <code>/web/app.php</code>. It'll force the change without modification to php.ini. It's a weird workaround, but it gets the job done.
