### ISSUE TITLE
chore: set demo up somewhere else (Heroku?)

### ISSUE THREAD

**Issue by maxfierke** [OfficeStack/OpenSkedge#91]

**Comment by gabeos** [comment]
Any progress on having a demo version?

**Comment by maxfierke** [comment]
Nope, sorry. Got super busy and this got buried. I'm adding a reminder now. I'll try getting it running on Heroku this weekend.

**Comment by maxfierke** [comment]
Finally got internet in my new place this week, so I'll try to get it running on Heroku or something else with a free-tier this weekend.

**Comment by maxfierke** [comment]
Demo is up and running on Heroku now.

Just moved the `demo.openskedge.org` name over to point to `blooming-reef-4418.herokuapp.com`. Might take a little while to propagate.
