### ISSUE TITLE
IP Manifest only detects localhost IP

### ISSUE THREAD

**Issue by auriculogenesis** [OfficeStack/OpenSkedge#96]
On a shared server, it seems that IP Manifest only detects localhost IP for Clock-In. For those running on a shared server, this may pose an issue for correctly clocking in users.

Current workaround:
Set localhost to allow for Time Clock and use the honor system. Employees can clock in on-time remotely even if they are running late. 

Other notes:
Clicking on "Set to Current IP Address" results in localhost IP being inputted.

**Comment by maxfierke** [comment]
I'm guessing the shared host is in a cluster setup behind a load-balancer or some other reverse-proxy type of setup. It's possible that the user's real IP is being set in the `X_FORWARDED_FOR` header. If you can get a reliable list of public IPs for your publically facing site, you can add them to the `trusted_proxies` list in the `framework` section of `app/config/config.yml`.

More info [here](http://symfony.com/doc/2.3/components/http_foundation/trusting_proxies.html)

**Comment by auriculogenesis** [comment]
Bingo, that did the trick :) Thank you!
